### ISSUE TITLE
Error in writing output to a document file

### ISSUE THREAD

**Issue by ramendra-sarma** [aravind-j/augmentedRCBD#11]
While wriring the outout to a Word fiel, the following error mesaage is seen.  How to resolve this issue?

Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  :

  PCDATA invalid Char value 27 [9]

**Comment by aravind-j** [comment]
Fixed in [c441df52401916486b92d05d34ce4f24884059aa](https://github.com/aravind-j/augmentedRCBD/commit/c441df52401916486b92d05d34ce4f24884059aa).
