### ISSUE TITLE
Export to MS word problem

### ISSUE THREAD

**Issue by JamesJesusjames** [aravind-j/augmentedRCBD#13]
It shows
"Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
  PCDATA invalid Char value 27 [9]"
when i am trying to export my analysed data in augmentedrcbd bulk

**Comment by aravind-j** [comment]
This issue is already fixed (#12) but not yet in CRAN. Please try with the latest developmental version from github.
