### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Rajithanair-2301** [aravind-j/augmentedRCBD#14]
Error in if (grepl(gwstring1, x$warnings$GVA)) { : 
  the condition has length > 1
I am getting this error for some traits while analyzing the data in AugmentedRCBD.
Kindly guide me on this issue.

**Comment by aravind-j** [comment]
@Rajithanair-2301 Can you kindly provide a [reproducible example ](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219/3) for troubleshooting?
