### ISSUE TITLE
Incompatibility with next version of grid

### ISSUE THREAD

**Issue by thomasp85** [aravind-j/augmentedRCBD#2]
We have been working on a new and faster implementation of the `unit` class for the upcoming release of R. This has now been merged into R-devel and testing shows that your package fails with the new unit implementation.

It appears that you are grabbing the non-exported `unit.list()` function here:

https://github.com/aravind-j/augmentedRCBD/blob/44d3f8753ec789ae5d85b89edf9d449f61224fa2/R/freqdist.augmentedRCBD.R#L189

`unit.list()` was never meant to be called directly and it has been removed as part of the rewrite, so your code fails. It is unclear to me why you need the functionality in the first place? If you describe your thinking I might be able to suggest a good work-around

**Comment by aravind-j** [comment]
It was used to extract the units from a `ggplot2` `grob`. I have fixed it to work with the updated implementation of `unit`.
