### ISSUE TITLE
exporting the output

### ISSUE THREAD

**Issue by shanmugavadivelps** [aravind-j/augmentedRCBD#3]
I am trying to export the output of "out1 <- augmentedRCBD(blk, trt, PH, method.comp = "lsd",
                      alpha = 0.05, group = TRUE, console = TRUE)")' 

as 

# save output to a separate .csv file
write.csv(out1, file="PH2016.csv)

but getting an error as below,

Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"augmentedRCBD"’ to a data.frame

pls help me to solve the issue

**Comment by aravind-j** [comment]
The function `write.csv` exports a matrix or a data.frame from `R` as a csv file.

The output from [`augmentedRCBD`](https://aravind-j.github.io/augmentedRCBD/reference/augmentedRCBD.html) is a list (https://aravind-j.github.io/augmentedRCBD/reference/augmentedRCBD.html#value) and not a data.frame. However, some of the components of the output list are data.frames which can be exported using `write.csv`.

For example if you want export the adjusted means, try the following.
`write.csv(out1$Means, "PH2016_Means.csv")`

There is also a built in function [`report.augmentedRCBD`](https://aravind-j.github.io/augmentedRCBD/reference/report.augmentedRCBD.html) which will export all the components of the output as a [word file](https://aravind-j.github.io/augmentedRCBD/articles/Data_Analysis_with_augmentedRCBD.html#report-augmentedrcbd).

```
report.augmentedRCBD(aug = out1,
                     target = "PH2016_Output.docx")
```
