### ISSUE TITLE
downloading the package augmentedRCBD

### ISSUE THREAD

**Issue by deanmuungani** [aravind-j/augmentedRCBD#4]
Hi 

I am failing to download the package augmentedRCBD
Error: Failed to install 'augmentedRCBD' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’

Warning in install.packages :
  package ‘augmentedRCBD’ is not available (for R version 4.0.0)

**Comment by sonulangaya-zz** [comment]
Try to reinstall ‘backports’ first. Then try to run the code agin. This time skip the update option.

**Comment by deanmuungani** [comment]
Thank you,

I just reinstalled "backports" but still giving me this error

Error: Failed to install 'augmentedRCBD' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

**Comment by sonulangaya-zz** [comment]
Hi. 
Try to delete the package 'rlang' from the package installed directory. Then reinstall the package from CRAN network. This time while installing augmentedRCBD don't forgot to skip the update option for aforesaid packages. Hope it will Help.

**Comment by aravind-j** [comment]
`augmentedRCBD` is back on CRAN. Please update `R` to 4.0.1 or 4.0.2 and install from CRAN with the following command.

```
install.packages('augmentedRCBD', dependencies=TRUE)
```
