### ISSUE TITLE
 "checks" and "check.col" are of unequal lengths

### ISSUE THREAD

**Issue by ramendra-sarma** [aravind-j/augmentedRCBD#8]
What is wrong with my file to get that message while running the code 
```
asra_out <- augmentedRCBD.bulk(data = asra, block = "Block",
                           treatment = "Treatment", traits = c("DF","PH", "ST","NoP", "PL", "GP", "CP", "Fer", "YP"),     checks = NULL, alpha = 0.05, describe = TRUE,   freqdist = TRUE, gva = TRUE,
                           check.col = c("brown", "darkcyan", "forestgreen", "purple"),  console = TRUE)

Error in augmentedRCBD.bulk(data = asra, block = "Block", treatment = "Treatment",  :
  "checks" and "check.col" are of unequal lengths
```
[asra.xlsx](https://github.com/aravind-j/augmentedRCBD/files/5571770/asra.xlsx)

**Comment by aravind-j** [comment]
As specified by the error message, the number of ["checks"](https://aravind-j.github.io/augmentedRCBD/reference/augmentedRCBD.html#arguments:~:text=(Trait).-,checks,Character%20vector%20of%20the%20checks%20present%20in%20treatment%20levels.%20If%20not%20specified%2C%20checks%20are%20inferred%20from%20the%20data%20on%20the%20basis%20of%20number%20of%20replications%20of%20treatments%2Fgenotypes.) (= 5 as inferred from the data on the basis of number of replications of treatments/genotypes) and the number of colours specified in ["check.col"](https://aravind-j.github.io/augmentedRCBD/reference/augmentedRCBD.bulk.html#arguments:~:text=.-,check.col,The%20colour(s)%20to%20be%20used%20to%20highlight%20check%20values%20in%20the%20plot%20as%20a%20character%20vector.%20Must%20be%20valid%20colour%20values%20in%20R%20(named%20colours%2C%20hexadecimal%20representation%2C%20index%20of%20colours%20%5B1%3A8%5D%20in%20default%20R%20%60palette()%60%20etc.).,-console) (=4) do not match. 

Add another colour to "check.col" to get the desired result.

```
asra_out <- augmentedRCBD.bulk(data = asra, block = "Block",
                           treatment = "Treatment", traits = c("DF","PH", "ST","NoP", "PL", "GP", "CP", "Fer", "YP"),     checks = NULL, alpha = 0.05, describe = TRUE,   freqdist = TRUE, gva = TRUE,
                           check.col = c("brown", "darkcyan", "forestgreen", "purple", "salmon"),  console = TRUE)
```
